### ISSUE TITLE
I have errors while trying to build Kitura-todoList-master

### ISSUE THREAD

**Issue by AndrewCh** [IBM-Swift/Kitura-TodoList#20]
**System:**
Linux xyz-ubuntu 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Swift:**
Swift version 3.0-dev (LLVM dffa09ffd8, Clang 9f0d189820, Swift 1c720b8f84)
Target: x86_64-unknown-linux-gnu

I try to build Kitura-todoList-master on my system with this command
swift build -Xcc -fblocks

I have following errors
Compile Swift Module 'HeliumLogger' (1 sources)
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:14:14: error: argument labels '(bool:)' do not match any available overloads
        self.init(bool: value)
             ^   ~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:14:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(bool: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:18:14: error: argument labels '(double:)' do not match any available overloads
        self.init(double: value)
             ^   ~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:18:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(double: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:22:14: error: argument labels '(float:)' do not match any available overloads
        self.init(float: value)
             ^   ~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:22:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(float: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:26:14: error: argument labels '(integer:)' do not match any available overloads
        self.init(integer: value)
             ^   ~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:26:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(integer: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:30:14: error: argument labels '(unsignedLong:)' do not match any available overloads
        self.init(unsignedLong: value)
             ^   ~~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:30:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(unsignedLong: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:34:14: error: argument labels '(char:)' do not match any available overloads
        self.init(char: value)
             ^   ~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:34:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(char: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:38:14: error: argument labels '(unsignedChar:)' do not match any available overloads
        self.init(unsignedChar: value)
             ^   ~~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:38:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(unsignedChar: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:42:14: error: argument labels '(short:)' do not match any available overloads
        self.init(short: value)
             ^   ~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:42:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(short: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:46:14: error: argument labels '(unsignedShort:)' do not match any available overloads
        self.init(unsignedShort: value)
             ^   ~~~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:46:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(unsignedShort: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:50:14: error: argument labels '(int:)' do not match any available overloads
        self.init(int: value)
             ^   ~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:50:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(int: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:54:14: error: argument labels '(unsignedInt:)' do not match any available overloads
        self.init(unsignedInt: value)
             ^   ~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:54:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(unsignedInt: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:58:14: error: argument labels '(longLong:)' do not match any available overloads
        self.init(longLong: value)
             ^   ~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:58:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(longLong: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:62:14: error: argument labels '(unsignedLongLong:)' do not match any available overloads
        self.init(unsignedLongLong: value)
             ^   ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:62:14: note: overloads for 'NSNumber.init' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
        self.init(unsignedLongLong: value)
             ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:65:30: error: value of type 'NSNumber' has no member 'longValue'
    var intValue:Int {return self.longValue}
                             ^~~~ ~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:67:32: error: value of type 'NSNumber' has no member 'unsignedLongValue'
    var uintValue:UInt {return self.unsignedLongValue}
                               ^~~~ ~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:69:32: error: value of type 'NSNumber' has no member 'charValue'
    var int8Value:Int8 {return self.charValue}
                               ^~~~ ~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:71:34: error: value of type 'NSNumber' has no member 'unsignedCharValue'
    var uint8Value:UInt8 {return self.unsignedCharValue}
                                 ^~~~ ~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:73:34: error: value of type 'NSNumber' has no member 'shortValue'
    var int16Value:Int16 {return self.shortValue}
                                 ^~~~ ~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:75:36: error: value of type 'NSNumber' has no member 'unsignedShortValue'
    var uint16Value:UInt16 {return self.unsignedShortValue}
                                   ^~~~ ~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:77:39: error: cannot convert return expression of type 'Int' to return type 'Int32'
    var int32Value:Int32 {return self.intValue}
                                 ~~~~~^~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:79:36: error: value of type 'NSNumber' has no member 'unsignedIntValue'
    var uint32Value:UInt32 {return self.unsignedIntValue}
                                   ^~~~ ~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:81:34: error: value of type 'NSNumber' has no member 'longLongValue'
    var int64Value:Int64 {return self.longLongValue}
                                 ^~~~ ~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/NSExtension.swift:83:36: error: value of type 'NSNumber' has no member 'unsignedLongLongValue'
    var uint64Value:UInt64 {return self.unsignedLongLongValue}
                                   ^~~~ ~~~~~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:217:19: error: argument labels '(double:)' do not match any available overloads
          value = NSNumber(double: number)
                  ^       ~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:217:19: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
          value = NSNumber(double: number)
                  ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:220:19: error: argument labels '(long:)' do not match any available overloads
          value = NSNumber(long: number)
                  ^       ~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:220:19: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
          value = NSNumber(long: number)
                  ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:358:31: error: value of type 'NSNumber' has no member 'longLongValue'
                return String(number.longLongValue)
                              ^~~~~~ ~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1199:28: error: argument labels '(double:)' do not match any available overloads
                    return NSNumber(double: decimal)
                           ^       ~~~~~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1199:28: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
                    return NSNumber(double: decimal)
                           ^
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1202:28: error: argument labels '(double:)' do not match any available overloads
                    return NSNumber(double: 0.0)
                           ^       ~~~~~~~~~~~~~
/home/andreich/Downloads/Kitura-TodoList-master/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1202:28: note: overloads for 'NSNumber' exist with these partially matching parameter lists: (coder: NSCoder), (integerLiteral: Int), (floatLiteral: Double), (booleanLiteral: Bool), (value: Bool), (value: Double), (value: Float), (value: Int), (value: UInt), (value: Int8), (value: UInt8), (value: Int16), (value: UInt16), (value: Int32), (value: UInt32), (value: Int64), (value: UInt64)
                    return NSNumber(double: 0.0)
                           ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/andreich/Downloads/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/andreich/Downloads/Kitura-TodoList-master/.build/debug.yaml

Any suggestions?
Thanks

**Comment by shmuelk** [comment]
@AndrewCh It looks like you are using the 05/09 driver of Swift 3.0. We are in the midst of a migration to the 05/09 driver of Swift 3.0. We should be done with this migration in a day or two.

The develop branch of Kitura-TodoList is compatible with the 05/03 driver of Swift 3.0.

**Comment by rfdickerson** [comment]
Can you try again @AndrewCh and let us know if it works?
