### ISSUE TITLE
Recommended project template for XCode

### ISSUE THREAD

**Issue by da-na** [IBM-Swift/Kitura-TodoList#4]
Hi! 
I'd love to open the source code of this project in XCode and be able to jump around the definitions and functions (simply use the miracle of indexing :)) I've been trying to figure out how to import it, but with no luck. Any helpful ideas? Would be great if they land in the readme!

**Comment by rfdickerson** [comment]
We are working on preparing a blog or some instructions to handle this.

IBM-Swift/Kitura#272

**Comment by rfdickerson** [comment]
Fixed with IBM-Swift/Kitura#272
