### ISSUE TITLE
Errors compiling Kitura

### ISSUE THREAD

**Issue by eytanschulman** [IBM-Swift/Kitura-TodoList#5]
I've tried to follow the tutorial for the ToDo app, and was told that the "Kitura" module was not imported, so I added the it as a dependency in my Packages.swift file: `.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 5)`

When I run `swift build -Xcc -fblocks -Xswiftc -I/usr/local/include -Xlinker -L/usr/local/lib`, I get this output:
https://gist.github.com/eytanschulman/a8b4443e86261b834d61

**Comment by rfdickerson** [comment]
Try now. Sorry about that, we did some API changes and Kitura-TodoList isn't hooked up to our normal CI.

**Comment by eytanschulman** [comment]
@rfdickerson Thanks,

Once I deleted my packages, made sure the Packages.swift file was the same as yours and rebuilt, I get this output: https://gist.github.com/eytanschulman/2c5a45f2a16a8222b5ee

**Comment by rfdickerson** [comment]
That's weird, if you are using the latest Package.swift that uses the minor version 0.6 it should have changed the API from use to all to correctly build this project.

https://github.com/IBM-Swift/Kitura-TodoList/blob/master/Package.swift
